trigger:
- main

pool:
   vmImage: ubuntu-latest
container: mcr.microsoft.com/playwright:v1.41.1-jammy

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: npx playwright test
  displayName: 'Run Playwright tests'
  env:
    CI: 'true'